-- AlterTable
ALTER TABLE "Settings" ADD COLUMN     "kitchenAutoPrint" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "kitchenAutoRefreshSeconds" INTEGER NOT NULL DEFAULT 45,
ADD COLUMN     "kitchenShowAgeBands" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "paymentAllowOverpay" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "paymentAllowZero" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "paymentDefaultMethod" TEXT NOT NULL DEFAULT 'cash',
ADD COLUMN     "posAutoOpenCheckout" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "posDefaultOrderType" TEXT NOT NULL DEFAULT 'dine_in',
ADD COLUMN     "posRequireTableSelection" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "receiptPaperSize" TEXT NOT NULL DEFAULT '80mm',
ADD COLUMN     "receiptShowBalance" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "receiptShowDiscounts" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "receiptShowItemNotes" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "refundMaxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "refundRequireManagerPin" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "securityAllowUserSwitching" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "securityInactivityLockMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "securityInactivityLogoutMinutes" INTEGER NOT NULL DEFAULT 0;
